package com.lasagnerd.odin.codeInsight.typeSystem;

public enum TsOdinTypeKind {
    ALIAS,
    ARRAY,
    BIT_FIELD,
    BIT_SET,
    BOOL,
    BUILTIN,
    ENUM,
    MAP,
    MATRIX,
    MULTI_POINTER,
    NUMERIC,
    PACKAGE,
    POINTER,
    POLYMORPHIC,
    PROCEDURE,
    PSEUDO_METHOD,
    RAWPTR,
    RUNE,
    SLICE,
    STRING,
    STRUCT,
    UNION,
    UNKNOWN,
    UNDECIDED,
    VOID,
    PROCEDURE_GROUP,
    DISTINCT_TYPE,
    DYNAMIC_ARRAY,
    SOA_SLICE,
    SOA_STRUCT,
}
